baseURL: https://lennartr.netlify.app/
languageCode: en-us
title: Lennart´s Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's Go!
    subtitle: |-
      A portfolio website by me and about me
    title: Hi, my name is Lennart and welcome to my portfolio website - happy to have you here!
  blog: {}
  contact: 
    address:
      - city: Notmycity
        country: United Kingdom
        street: Notmystreet 666
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lrath.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (666) 666-666
        title: Phone
  custom_css: []
  custom_js: []
  description: This is the portfolio website I would like to use to introduce you to my R competencies.
  error404:
    heading: Page couldn't be found
    text: Please go back home [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    #quicklinks:
     # - alt: HTML5 UP
     #   text: 'Thanks to HTML5UP for the free design!'
     #   url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/rath.lennart/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/lennartra
      - icon: fa-github
        label: GitHub
        url: https://github.com/LennartRath
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lennart-rath/
  image: 'LBS.jfif'
  name: Lennart R
  navigation:
    button1:
      - name: My work
        url: Contents
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: Contents
        url: Contents
      #- name: Generic Blog
      #  url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: Data Science is fun!
    title: Lennart's Portfolio
  tiles:
    enable: yes
    showcase:
      - image: LennartRath.jpg
        subtitle: Learn about me!
        title: About me
        url: blogs/aboutme
      - image: Grouppic.jpeg
        subtitle: Things Lennart likes
        title: Enjoyable things
        url: blogs/njoy
      - image: yield_curve.jpg
        subtitle: Case Study Yield Curve Inversion
        title: Yield Curve Inversion
        url: blogs/yieldcurve
      - image: Rio.jpg
        subtitle: Case Study AirBnB in Rio de Janeiro
        title: RIO
        url: blogs/rio

  two:
    buttonText: Lets goooo!
    enable: yes
    subtitle: "Enough said - let us now get into the contents of my website. Above you find links to my different showcases. Have fun!"
    title: Contents of this website
    url: blogs
