baseURL: https://lennartr.netlify.app/
languageCode: en-us
title: Lennart´s Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Lennart and welcome to my portfolio website - happy to have you here!
  blog: {}
  contact: 
    address:
      - city: Notmycity
        country: United Kingdom
        street: Notmystreet 666
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lrath.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (666) 666-666
        title: Phone
  custom_css: []
  custom_js: []
  description: This is the portfolio website I would like to use to introduce you to my R competencies.
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'THanks to HTML5UP for the free design!'
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/rath.lennart/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/lennartra
      - icon: fa-github
        label: GitHub
        url: https://github.com/LennartRath
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lennart-rath/
  image: 'LBS.jif'
  name: Lennart R
  navigation:
    button1:
      - name: My work
        url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Portfolio Site
  tiles:
    enable: yes
    showcase:
      - image: lbs.jfif
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum

  two:
    buttonText: I am getting started!
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
